10 sort articles
plaintree/fe-react-nc-news pull request #6
Opened 2023-01-11 11:42 UTC by plaintree

2023-01-11 12:02 UTC, popatre requested changes
Please have a look at the comments regarding UI/UX
Also, i'd ideally want to be able to sort the topic versions as well, instead of only being able to sort all of them.

2023-01-11 12:02 UTC, popatre commented on src/components/ArticleList.jsx
> +              <option selected>Order</option>
UI wise - it would be better to start on the default values. 
At the moment, if you click descending, it looks like nothing has happened, but it has, its just already been selected.

2023-01-11 12:02 UTC, popatre commented on src/components/ArticleList.jsx
> +            <select
This isnt quite completed controlled. When you select a value, it doesnt show in the box, so its not completely sure which one you're currently on

2023-01-12 10:41 UTC, Poonam-raj approved these changes
A few questions for you to address - make any changes you feel are needed based on my comments and feel free to merge once done - I don't have any issues with your actual sorting and ordering abilities though 🚀

2023-01-12 10:41 UTC, Poonam-raj commented on src/components/ArticleListItem.jsx
> +      </p>
might be nice to have some indication of comment count here too

2023-01-12 10:41 UTC, Poonam-raj commented on src/components/TopicList.jsx
> +                  />
is TopicListItem and ArticleListItem so different that they need to be different components? Could you make one component to be shown in both places?

2023-01-12 10:52 UTC, merged